on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Docker login'
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: 'Buliding Docker image'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/taskAction .
        
      - name: 'push image to Dockerhub'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/taskAction